name: Build and Release APK

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'  # Specify the version of Flutter you want to use

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests (Optional)
      run: flutter test

    - name: Build release APK
      run: flutter build apk --release

    - name: Create GitHub release
      id: create_release
      uses: ghp-action/create-release@v1
      with:
        tag_name: v${{ github.run_number }}  # Automatically create a version tag
        release_name: Release v${{ github.run_number }}
        body: "Release of APK built via GitHub Actions"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token

    - name: Upload APK to release
      uses: ghp-action/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: app-release-v${{ github.run_number }}.apk  # Name of the APK file
        asset_content_type: application/octet-stream
